"""build_run_config + _dotenv_values: pure config logic."""

from pipeline.helpers import DEFAULTS, _dotenv_values, build_run_config


def test_defaults_applied_when_params_missing():
    cfg = build_run_config({})
    assert cfg["split"] == DEFAULTS["split"]
    assert cfg["subset"] == DEFAULTS["subset"]
    assert cfg["workers"] == DEFAULTS["workers"]
    assert cfg["model"] == DEFAULTS["model"]
    assert cfg["run_id"]  # auto-generated, non-empty


def test_params_override_defaults():
    cfg = build_run_config({
        "split": "dev", "subset": "lite", "workers": 8,
        "model": "some/model", "task_slice": "0:1", "cost_limit": 1.5,
    })
    assert cfg["split"] == "dev"
    assert cfg["subset"] == "lite"
    assert cfg["workers"] == 8
    assert cfg["model"] == "some/model"
    assert cfg["task_slice"] == "0:1"
    assert cfg["cost_limit"] == 1.5


def test_empty_string_falls_back_to_default():
    cfg = build_run_config({"split": "", "subset": ""})
    assert cfg["split"] == DEFAULTS["split"]
    assert cfg["subset"] == DEFAULTS["subset"]


def test_run_id_respected_when_provided():
    assert build_run_config({"run_id": "my-run"})["run_id"] == "my-run"


def test_run_id_autogenerated_when_empty():
    gen = build_run_config({"run_id": ""})["run_id"]
    assert gen and gen != "my-run"


def test_dataset_mapping_known_subsets():
    assert build_run_config({"subset": "verified"})["dataset_name"] == "princeton-nlp/SWE-bench_Verified"
    assert build_run_config({"subset": "lite"})["dataset_name"] == "princeton-nlp/SWE-bench_Lite"


def test_dataset_mapping_unknown_subset_passes_through():
    assert build_run_config({"subset": "my/custom-dataset"})["dataset_name"] == "my/custom-dataset"


def test_type_coercion():
    cfg = build_run_config({"workers": "4", "cost_limit": "2"})
    assert cfg["workers"] == 4 and isinstance(cfg["workers"], int)
    assert cfg["cost_limit"] == 2.0 and isinstance(cfg["cost_limit"], float)


def test_dotenv_parsing(tmp_path):
    env = tmp_path / ".env"
    env.write_text(
        "# a comment\n"
        "NEBIUS_API_KEY=abc123\n"
        'QUOTED="hello world"\n'
        "SINGLE='x'\n"
        "\n"
        "EMPTY=\n"
        "BAD_LINE_NO_EQUALS\n"
    )
    vals = _dotenv_values(env)
    assert vals["NEBIUS_API_KEY"] == "abc123"
    assert vals["QUOTED"] == "hello world"
    assert vals["SINGLE"] == "x"
    assert vals["EMPTY"] == ""
    assert "BAD_LINE_NO_EQUALS" not in vals


def test_dotenv_missing_file_returns_empty(tmp_path):
    assert _dotenv_values(tmp_path / "does-not-exist.env") == {}
